[package]
name = "slot-range-helper"
edition="2021"
version="0.9.36"

[dependencies]
paste = "1.0"
enumn = "0.1.5"
parity-scale-codec = { version = "3.1.5", default-features = false, features = ["derive"] }
sp-std = { package = "sp-std", git = "https://github.com/paritytech/substrate", default-features = false , branch = "polkadot-v0.9.36" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "polkadot-v0.9.36" }

[features]
default = ["std"]
std = [
	"sp-std/std",
	"parity-scale-codec/std",
	"sp-runtime/std",
]
